### ISSUE TITLE
ANPRC actions broken

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#300]

**Comment by odkupiciel375** [comment]
> > opened on may31
> 
> is it still dead?

As far as I know, it is not. However, one action is now broken - folding the antenna - due to an issue with prc animations where loading such model to proc anim editor will crash whole wb (this only occurs in current experimental build while in stable it works fine). This issue has been reported to BI, and until it gets resolved, that action will be hidden.
