### ISSUE TITLE
NPE on opening inventory

### ISSUE THREAD

**Issue by ajvorobiev** [RHSMODS/statusquo#508]
![image](https://github.com/RHSMODS/statusquo/assets/7216776/0d554268-fc91-4758-b0d4-519d3f5fdefe)

in test world, equip an ECH that has the separate Peltors from the table. Open inventory.

Edit: correction. Use the Pick Up action to place the ECH into the inventory, rather than equip

Edit2: seems to just happen when you spawn and open the inventory

**Comment by odkupiciel375** [comment]
Issue seems to be only happening with MSV soldiers (fe. SL) while USMC loadouts are unaffected. According to the debug tests there seems to be some item in MSV loadout that is inside player inventory (top level - like backpack or boots) and it doesnt have InventoryItemComponent and since BI check for type then it will throw NPE .
![image](https://github.com/RHSMODS/statusquo/assets/19805800/69d615ad-9afc-45a9-a0cb-d3fe54f80e9f)
Ill try to find it

**Comment by odkupiciel375** [comment]
Issue is caused by PDU4 and it seems like all rangefinders are borked
![image](https://github.com/RHSMODS/statusquo/assets/19805800/c3ee8338-dd0d-4b72-94b2-505abdad492d)
