### ISSUE TITLE
Running different scenario using RHSSQ

### ISSUE THREAD

**Issue by Spinfxr** [RHSMODS/statusquo#577]
Hi,

I tried to run a standard conflict scenario using the RHSSQ  mod but not a RHS scenario, but the weapons and gear doesn't show up in the arsenal .

Is there trick to it ?

Any help would be appreciated.

Spin

**Comment by Spinfxr** [comment]
ok .. I don't have to the skills for that. Seems strange that you would have to do that since nearly every other mod can used in all standard scenarios. Why would teh mod  makers lock it in.

**Comment by reyhard** [comment]
"Seems strange that you would have to do that since nearly every other mod can used in all standard scenarios. Why would the mod makers lock it in "
Reason is quite easy - a lot of mods are adding all kind of gear to vanilla coldwar US & USSR crates which crates kind of mess, when you want to play Cold War scenario. 
You can read about adding stuff to Entity Catalog over here https://community.bistudio.com/wiki/Arma_Reforger:Weapon_Creation/Prefab_Configuration#Adding_to_existing_crates

**Comment by Spinfxr** [comment]
ok Thanks for your reply.

**Comment by Spinfxr** [comment]
I see dark gru are able to use on their server  mission without making RHSSQ as a dependent. So there must be a way aside your advice above. Maybe someone else can help me ?
